language: node_js
node_js:
- '6.0'
before_install:
- npm install -g jspm@0.16.32
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
env:
  global:
    secure: K0ipMS02npgm/Wr6QmS5e6pFQYgUfblIGtBsT4/PBItOapxuLqbqkIR/yJHdpYsag2KQagtoJ9oSVQ7aU0UEjk44Abq4SO7884xpKzqIU4F7PYhLDD0+d2sKeuv0SmiarbzWrI6AoQHp56aXhQxKGr3rti6znLagCv8Ou3GqsLvzc/mOpGNpWIimAFrvyeJs3C6SWSJzAChLOdt04H6K7H8LhFxMyMpBRu4UQSOCBb7XazJopmAdsGwtgQ825pVIfa1ewjEbVy1Mk35XWEV2dxVUtC+TpomR1pKkh/cQh/miOrTIAqf5PIg/iCJr616f1FjVNRs+j0EgF3aytWxOUnHSzvP1huajf5EtutVOtSKGBG+qUzupQQZtD+Ujr9C8+7I14NEVl0GBPkA05qlnJBxbpAVgbKTbNz/u9MtWDjw0b1JfEZYvGN/4t8wr82mFaKcYD21iYsnFv+fHKJ0SuWdktMK9ZGN92ovjC1shduFHnRG1XPcGwAjAi2x6pO/e1TBdugraTVoAyV83blhovXMfPmq6KpKuYJ9nwfL6O0XpiFzyZwhLrVGklnLp4xZnKk4pORnR2lqkSq39Uzqv1VFjFg4rdOtTiUMPBJDUWS7TfuBMnUTJdlXGLz3a6tMMF124f/OlwzT4N54CtLtHDmiX3+C0MlPtO/oceDLejC4=
